title: "Beek Labs"
author: "beeklabs"
description: "All rights reserved"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
url: https://blog.beeklabs.com/

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:beeklabs@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/BeekLabs"}
  - {title: Web, icon: filter, url: "https://beeklabs.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 
# Google Analytics
google_analytics: G-K4R2X4HBZV
